### ISSUE TITLE
problem running syncabook

### ISSUE THREAD

**Issue by ghost** [r4victor/syncabook#15]
whenever i run syncabook -h, it shows me this-

D:\Downloads\syncabook\syncabook>syncabook -h
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\syncabook-script.py", line 33, in <module>
    sys.exit(load_entry_point('syncabook==0.1.1', 'console_scripts', 'syncabook')())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\syncabook-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\syncabook-0.1.1-py3.10.egg\syncabook\__main__.py", line 3, in <module>
    from .create import create_ebook
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\syncabook-0.1.1-py3.10.egg\syncabook\create.py", line 9, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by r4victor** [comment]
@avijitb129, it seems `beautifulsoup4` is not installed. It should be installed automatically when you do `pip install .` to install `syncabook`. Try reinstalling it and look for error messages during installation. And I'd recommend using `syncabook` with Docker to avoid such issues.

Note also, that for the sync step you need the `afaligner` library that is not tested on Windows. You may need to use a VM.
