### ISSUE TITLE
error on FastDTWBDError, plz help

### ISSUE THREAD

**Issue by Tianxu-Jia** [r4victor/syncabook#31]
File "/usr/local/lib/python3.9/site-packages/afaligner/c_dtwbd_wrapper.py", line 49, in c_FastDTWBD
    raise FastDTWBDError(
afaligner.c_dtwbd_wrapper.FastDTWBDError: The FastDTWDB() C function raised an error. See stderr for more details.

**Comment by Tianxu-Jia** [comment]
ERROR: malloc() failed when allocating D_matrix
Traceback (most recent call last):
  File "/usr/local/bin/syncabook", line 8, in <module>
Calling afaligner for syncing...
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/syncabook/__main__.py", line 157, in main
    sync(
  File "/usr/local/lib/python3.9/site-packages/syncabook/sync.py", line 15, in sync
    sync_map = align(
  File "/usr/local/lib/python3.9/site-packages/afaligner/__init__.py", line 92, in align
    sync_map = build_sync_map(
  File "/usr/local/lib/python3.9/site-packages/afaligner/__init__.py", line 211, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "/usr/local/lib/python3.9/site-packages/afaligner/c_dtwbd_wrapper.py", line 49, in c_FastDTWBD
    raise FastDTWBDError(
afaligner.c_dtwbd_wrapper.FastDTWBDError: The FastDTWDB() C function raised an error. See stderr for more details.
